# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START cloudbuild_maven]
steps:
  # Step 1: Install Node.js
#  - name: 'node:14.17.6'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        pwd
#        npm install -g npm@8.1.2
#
#  # Step 2: Install Angular CLI (if not already cached)
#  - name: 'node:14.17.6'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        npm install -g @angular/cli
#
#  # Step 3: Install dependencies and build Angular project
#  - name: 'node:14.17.6'  # Ensure Node.js version matches previous step
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        npm cache clean --force
#        npm install
#        ng update --all --force
#        npm run build -- --prod

  # Step 4: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/frontend:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 5: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/frontend:latest'

  # Step 6: Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './deployment.yaml'  # Path to your Kubernetes deployment YAML file
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=africa-south1-a'  # Replace with your GCP zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=doantotnghiep'  # Replace with your GKE cluster name

images:
  - 'gcr.io/$PROJECT_ID/my-angular-app:$COMMIT_SHA'
# [END cloudbuild_maven]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _CLUSTER: 'doantotnghiep'
  _ZONE: 'africa-south1-a'
