apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: minhkq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/frontend:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: minhkq
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP
