apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: minhkq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: africa-south1-docker.pkg.dev/doantotnghiep-426507/doantotnghiep-repo/backend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: minhkq
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
